pretrained_model_path: "/home/jsh/neurips/Video-P2P-main/stable-diffusion-v1-5"
output_dir: "/database/jeong_seong_hun/WACV2024/videos/videop2p_output/0531/red_car_1"

train_data:
  video_path: "/home/jsh/neurips/Video-P2P-combined/data/parking_new"
  prompt: "There is a car moving"
  n_sample_frames: 4
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "There is a red car moving"
  video_length: 4
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 300
checkpointing_steps: 1000
validation_steps: 300
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
